name: flutter_map_tappable_polyline
description: A flutter_map plugin that adds Polyline class with onTap event
version: 1.1.0
homepage: https://github.com/OwnWeb/flutter_map_tappable_polyline

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1

dev_dependencies:
  pedantic: ^1.9.2
