name: flutter_map_tappable_polyline
description: A flutter_map plugin that adds Polyline class with onTap event
version: 6.0.0
homepage: https://github.com/OwnWeb/flutter_map_tappable_polyline

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.1
  latlong2: ^0.9.0

dev_dependencies:
  pedantic: ^1.11.1
